[alembic]
script_location = alembic
file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s
prepend_sys_path = .
timezone = UTC
sqlalchemy.url = postgresql+asyncpg://postgres:postgres_password@localhost:5432/funding_platform

[post_write_hooks]

[logging]
default_levelname = INFO
