"""
Export & Report Generator Service (PDF, CSV/Excel HTML generator)
"""

import io
import csv
from typing import List, Dict, Any


class ExportService:

    @staticmethod
    def generate_csv_report(headers: List[str], rows: List[List[Any]]) -> str:
        """
        Generates clean CSV text formatted for Excel / spreadsheet tools.
        """
        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow(headers)
        for r in rows:
            writer.writerow(r)
        return output.getvalue()

    @staticmethod
    def generate_printable_html_report(title: str, subtitle: str, content_html: str) -> str:
        """
        Generates a clean, styled HTML report ready for printing or saving as PDF.
        """
        return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{title}</title>
    <style>
        body {{ font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #1e293b; background: #ffffff; }}
        .header {{ border-bottom: 2px solid #2563eb; padding-bottom: 15px; margin-bottom: 30px; }}
        h1 {{ font-size: 24px; color: #0f172a; margin: 0 0 5px 0; }}
        .subtitle {{ font-size: 14px; color: #64748b; margin: 0; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
        th, td {{ padding: 10px 14px; text-align: left; border-bottom: 1px solid #e2e8f0; font-size: 13px; }}
        th {{ background-color: #f8fafc; color: #334155; font-weight: 600; }}
        .badge {{ display: inline-block; padding: 4px 8px; border-radius: 4px; font-size: 11px; font-weight: bold; background: #e0f2fe; color: #0369a1; }}
        .footer {{ margin-top: 50px; font-size: 11px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 15px; text-align: center; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>{title}</h1>
        <p class="subtitle">{subtitle} | Generated by Research Funding & Innovation Intelligence Platform</p>
    </div>
    <div class="content">
        {content_html}
    </div>
    <div class="footer">
        Confidential & Proprietary Innovation Intelligence Briefing | Page 1 of 1
    </div>
</body>
</html>"""
