"""add pdf path to publications

Revision ID: 071c21aab268
Revises: b584a3971426
Create Date: 2026-07-27 12:20:49.298263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '071c21aab268'
down_revision: Union[str, Sequence[str], None] = 'b584a3971426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('pdf_path', sa.String(length=1000), nullable=True))
    op.create_index(op.f('ix_publications_research_profile_id'), 'publications', ['research_profile_id'], unique=False)
    op.drop_constraint(op.f('publications_research_profile_id_fkey'), 'publications', type_='foreignkey')
    op.create_foreign_key(None, 'publications', 'research_profiles', ['research_profile_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'publications', type_='foreignkey')
    op.create_foreign_key(op.f('publications_research_profile_id_fkey'), 'publications', 'research_profiles', ['research_profile_id'], ['id'])
    op.drop_index(op.f('ix_publications_research_profile_id'), table_name='publications')
    op.drop_column('publications', 'pdf_path')
    # ### end Alembic commands ###
