"""create research keywords table

Revision ID: 321fcbb92c4f
Revises: acfee6748407
Create Date: 2026-07-09 15:16:21.302332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '321fcbb92c4f'
down_revision: Union[str, Sequence[str], None] = 'acfee6748407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['research_profile_id'], ['research_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('research_profile_id', 'name', name='uq_research_profile_keyword')
    )
    op.create_index(op.f('ix_research_keywords_id'), 'research_keywords', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_keywords_id'), table_name='research_keywords')
    op.drop_table('research_keywords')
    # ### end Alembic commands ###
