"""create patents table

Revision ID: 4fe3a94c2de1
Revises: a30b12231546
Create Date: 2026-07-09 22:02:25.290955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fe3a94c2de1'
down_revision: Union[str, Sequence[str], None] = 'a30b12231546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_profile_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('patent_number', sa.String(length=255), nullable=True),
    sa.Column('inventors', sa.Text(), nullable=True),
    sa.Column('patent_office', sa.String(length=255), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('grant_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['research_profile_id'], ['research_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patent_number')
    )
    op.create_index(op.f('ix_patents_id'), 'patents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patents_id'), table_name='patents')
    op.drop_table('patents')
    # ### end Alembic commands ###
