"""update startup profile

Revision ID: 550c36816bfb
Revises: cc41ebe867be
Create Date: 2026-08-05 10:15:06.638767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '550c36816bfb'
down_revision: Union[str, Sequence[str], None] = 'cc41ebe867be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('startups', sa.Column('founded_year', sa.Integer(), nullable=False))
    op.add_column('startups', sa.Column('funding_stage', sa.String(length=100), nullable=False))
    op.add_column('startups', sa.Column('startup_email', sa.String(length=255), nullable=False))
    op.add_column('startups', sa.Column('phone_number', sa.String(length=30), nullable=False))
    op.add_column('startups', sa.Column('linkedin_url', sa.String(length=255), nullable=False))
    op.add_column('startups', sa.Column('technology_stack', sa.Text(), nullable=False))
    op.add_column('startups', sa.Column('research_interests', sa.Text(), nullable=False))
    op.add_column('startups', sa.Column('team_size', sa.Integer(), nullable=False))
    op.add_column('startups', sa.Column('pitch_deck_url', sa.String(length=255), nullable=False))
    op.add_column('startups', sa.Column('logo_url', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('startups', 'logo_url')
    op.drop_column('startups', 'pitch_deck_url')
    op.drop_column('startups', 'team_size')
    op.drop_column('startups', 'research_interests')
    op.drop_column('startups', 'technology_stack')
    op.drop_column('startups', 'linkedin_url')
    op.drop_column('startups', 'phone_number')
    op.drop_column('startups', 'startup_email')
    op.drop_column('startups', 'funding_stage')
    op.drop_column('startups', 'founded_year')
    # ### end Alembic commands ###
