"""create funding opportunities table

Revision ID: 76053dc22316
Revises: 4fe3a94c2de1
Create Date: 2026-07-17 12:04:11.165298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76053dc22316'
down_revision: Union[str, Sequence[str], None] = '4fe3a94c2de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funding_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.Column('funding_type', sa.String(length=100), nullable=True),
    sa.Column('research_domain', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('funding_amount', sa.String(length=100), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('official_link', sa.String(length=1000), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('eligible_countries', sa.Text(), nullable=True),
    sa.Column('international_applicants_allowed', sa.Boolean(), nullable=False),
    sa.Column('career_stage', sa.String(length=255), nullable=True),
    sa.Column('qualification', sa.String(length=255), nullable=True),
    sa.Column('experience_required', sa.Integer(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_opportunities_id'), 'funding_opportunities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_funding_opportunities_id'), table_name='funding_opportunities')
    op.drop_table('funding_opportunities')
    # ### end Alembic commands ###
