"""create research profiles table

Revision ID: 838b0b1da49a
Revises: ed312ffa24e3
Create Date: 2026-07-06 16:49:45.719960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '838b0b1da49a'
down_revision: Union[str, Sequence[str], None] = 'ed312ffa24e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('highest_qualification', sa.String(length=150), nullable=True),
    sa.Column('current_position', sa.String(length=150), nullable=True),
    sa.Column('organization_name', sa.String(length=255), nullable=True),
    sa.Column('orcid_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orcid_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_research_profiles_id'), 'research_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_profiles_id'), table_name='research_profiles')
    op.drop_table('research_profiles')
    # ### end Alembic commands ###
