"""create technology areas table

Revision ID: 9afa9711d50f
Revises: 321fcbb92c4f
Create Date: 2026-07-09 15:35:37.517589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9afa9711d50f'
down_revision: Union[str, Sequence[str], None] = '321fcbb92c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technology_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['research_profile_id'], ['research_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('research_profile_id', 'name', name='uq_research_profile_technology_area')
    )
    op.create_index(op.f('ix_technology_areas_id'), 'technology_areas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technology_areas_id'), table_name='technology_areas')
    op.drop_table('technology_areas')
    # ### end Alembic commands ###
