"""create research domains table

Revision ID: acfee6748407
Revises: 838b0b1da49a
Create Date: 2026-07-09 14:41:55.157697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acfee6748407'
down_revision: Union[str, Sequence[str], None] = '838b0b1da49a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['research_profile_id'], ['research_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('research_profile_id', 'name', name='uq_research_profile_domain')
    )
    op.create_index(op.f('ix_research_domains_id'), 'research_domains', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_domains_id'), table_name='research_domains')
    op.drop_table('research_domains')
    # ### end Alembic commands ###
