"""add researcher publication library

Revision ID: b584a3971426
Revises: efec1f51232a
Create Date: 2026-07-22 17:02:11.092884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b584a3971426'
down_revision: Union[str, Sequence[str], None] = 'efec1f51232a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researcher_imported_publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_profile_id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_profile_id'], ['research_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('research_profile_id', 'publication_id', name='uq_researcher_imported_publication')
    )
    op.create_index(op.f('ix_researcher_imported_publications_id'), 'researcher_imported_publications', ['id'], unique=False)
    op.create_index(op.f('ix_researcher_imported_publications_publication_id'), 'researcher_imported_publications', ['publication_id'], unique=False)
    op.create_index(op.f('ix_researcher_imported_publications_research_profile_id'), 'researcher_imported_publications', ['research_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_researcher_imported_publications_research_profile_id'), table_name='researcher_imported_publications')
    op.drop_index(op.f('ix_researcher_imported_publications_publication_id'), table_name='researcher_imported_publications')
    op.drop_index(op.f('ix_researcher_imported_publications_id'), table_name='researcher_imported_publications')
    op.drop_table('researcher_imported_publications')
    # ### end Alembic commands ###
