"""create startup table

Revision ID: cc41ebe867be
Revises: 071c21aab268
Create Date: 2026-08-04 19:38:58.484228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc41ebe867be'
down_revision: Union[str, Sequence[str], None] = '071c21aab268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('startups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('startup_name', sa.String(length=200), nullable=False),
    sa.Column('tagline', sa.String(length=250), nullable=False),
    sa.Column('industry', sa.String(length=150), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=False),
    sa.Column('funding_needed', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_startups_id'), 'startups', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_startups_id'), table_name='startups')
    op.drop_table('startups')
    # ### end Alembic commands ###
