"""support external publications

Revision ID: efec1f51232a
Revises: 4443f1711e56
Create Date: 2026-07-22 16:52:08.419359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efec1f51232a'
down_revision: Union[str, Sequence[str], None] = '4443f1711e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publications', 'research_profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publications', 'research_profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
